### ISSUE TITLE
Rcurl::url.exists() in dowloadData can't find existing URL

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.tools#29]
`Rcurl::url.exists()` is having trouble finding URLs that do exist. This has happened to others (see [here](https://stackoverflow.com/questions/40391047/why-url-exists-returns-false-when-the-url-does-exists-using-rcurl). Although the problem can be fixed, the fix seems a bit cumbersome and perhaps OS dependent?
Should we use the `httr` package instead?

Reproducible example (using SpaDES.tools@development OR tag = CEFWorkshop; using SpaDES.core tag = CEFWorkshop):
```
library(SpaDES.core)
library(SpaDES.tools)
downloadModule('LBMR', path = getPaths()$modulePath, repo = 'CeresBarros/SpaDES-modules', data = TRUE, overwrite = TRUE)
```
You'll notice that `downloadData `asks for the user to manually download ecoregions.gis from
https://github.com/LANDIS-II-Foundation/Extensions-Succession/raw/master/biomass-succession-archive/trunk/tests/v6.0-2.0/ecoregions.gis 

This is because
`Rcurl::url.exists("https://github.com/LANDIS-II-Foundation/Extensions-Succession/raw/master/biomass-succession-archive/trunk/tests/v6.0-2.0/ecoregions.gis")`
outputs FALSE, when it should be TRUE (try putting the link in your browser)

**Comment by CeresBarros** [comment]
A solution:
```
url <- "https://github.com/LANDIS-II-Foundation/Extensions-Succession/raw/master/biomass-succession-archive/trunk/tests/v6.0-2.0/ecoregions.gis"
http::http_error(url)
```

**Comment by achubaty** [comment]
We've gone back and forth on using Rcurl and httr. I can't recall exactly, but httr gave problems in some cases too. Whichever we decide to use, we need to check that we are using it consistently (I think we use a combination of both right now).

**Comment by CeresBarros** [comment]
Is it so problematic to use both? Since they present problems in different cases, perhaps we need to use both?

**Comment by achubaty** [comment]
Not necessarily a problem, but it's easier to manage future updates, especially from (external) dependency packages, if we are relying on as few moving parts as possible.

**Comment by CeresBarros** [comment]
Done in PR
