### ISSUE TITLE
adj test failures

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.tools#56]
Results vary each time test is run; intermittent failures

![29A9E2A9-9174-4991-ABC5-B7733F5B8FD3](https://user-images.githubusercontent.com/3435577/69342251-5acf9480-0c28-11ea-8a43-bad7a6e7b80b.jpeg)

@eliotmcintire CRAN asked us to fix this before 2019-12-05

**Comment by eliotmcintire** [comment]
closed with f86cf1f38169ce64055e3e44b5c055a9a936092d
