### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by cntrouniv** [PredictiveEcology/SpaDES.tools#68]
I am trying to install this package from the zip file in R Studio. It does not seem to be installing. When I execute the installation it runs but nothing gets added to my Packages. Wondered if anyone else has had this issue?

**Comment by achubaty** [comment]
Hi, can you please clarify how you are trying to install? Please provide the command you ram and any outputs.

What do you mean by zip file? Which zip file? Which version, from where?

The package has been momentarily archived on CRAN but the latest version was resubmitted and we expect it to be available shortly. In the mean time, you can install directly from GitHub:

remotes::install_github("PredictiveEcology/SpaDES.tools")

**Comment by cntrouniv** [comment]
Hi, I was sourcing installation files from cran at Imperial and downloaded off of this website but was not having any luck. I am running the installation using the command line you sent and this is the response  I get after running the install and then accessing the library:

> library(SpaDES.tools)
Error: package or namespace load failed for ‘SpaDES.tools’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘rlang’ 0.4.8 is already loaded, but >= 0.4.10 is required
In addition: Warning message:
package ‘SpaDES.tools’ was built under R version 4.0.5

**Comment by achubaty** [comment]
Per that error message, you need an updated version of rlang.
