### ISSUE TITLE
inconsistent columns in spread2() output

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.tools#74]
Two intermittent issues with the number of columns changing between `spread2()` calls:

1. `order` sometimes disappears from the output data.table, despite `plot.it = FALSE`;
2. `numNeighs` sometimes appears in the data.table.

My work around is to ensure `order` exists in the `outDT` (and I manually set the values as `1:nrow(outDT)`), and remove the `numNeighs` column if it appears, but I don't think these should be necessary.

**Comment by eliotmcintire** [comment]
If you can reproduce this, we can evaluate it. Currently, passing all unit tests so this may be captured.

Please re-open if you can find a reprex
