### ISSUE TITLE
Bug in cir

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.tools#8]
_From @eliotmcintire on April 26, 2017 22:6_

With `allowOverlap = TRUE`

No reproducible example here as it was embedded deep somewhere.

`cir(landscape, loci = fromPixels, includeBehavior = "excludePixels",
                             minRadius = resCur, maxRadius = 4*resCur, allowOverlap = TRUE)`

It identified vastly (10x-100x) too many cells.

_Copied from original issue: PredictiveEcology/SpaDES#342_

**Comment by achubaty** [comment]
@eliotmcintire was this resolved? I'm guessing not, but since there's no reprex, I can't be sure

**Comment by achubaty** [comment]
@eliotmcintire bumping this again. has this been dealt with?

**Comment by eliotmcintire** [comment]
Not done

**Comment by eliotmcintire** [comment]
I am going to close this because  1. It hasn't been seen since; 2. there are a lot of changes under the hood that may have affected this. and 3. there is no reprex
