### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [PredictiveEcology/SpaDES.tools#83]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

`SpaDES.tools` imports 'rgeos' `rgeos::gContains` as found by `pkgapi`, in NAMESPACE, in R/initialize.R line 271. My guess would be that `terra::relate` with coercion to and from `SpatVector` is closest, as you use `raster` and it imports `terra`. `sf` is suggested, and could to the same, but you already have the functionality in `terra` which is already an indirect strong dependency. Please fix best by June, latest October 2023.

**Comment by eliotmcintire** [comment]
This is almost complete.

**Comment by rsbivand** [comment]
Thanks!
